import json
import subprocess
import time


# a list of all the timestep files we put in hadoop
file_names = [
	'/preprocessed_hlists/hlist_0.06630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.07830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.09630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.10230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.10830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.11430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.12030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.13230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.13830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.14430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.15030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.15630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.16230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.16830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.17430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.18030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.18630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.19230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.19830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.20230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.20430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.21030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.21630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.22230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.22830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.23430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.24630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.25230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.25830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.26430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.27030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.27630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.28230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.28830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.29430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.30630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.31230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.31830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.32430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.33030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.33630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.34230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.34830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.35430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.36030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.36630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.37230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.37830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.38430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.39030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.39630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.40230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.40830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.41430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.42030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.42630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.43230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.43830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.44430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.45030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.45630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.46230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.46830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.47430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.48030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.48630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.49830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.50430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.51030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.51630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.52230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.52830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.53230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.53830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.54430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.55030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.55630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.56230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.56830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.57430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.58030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.58630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.59230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.59830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.60430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.61030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.61630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.62230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.62830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.63430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.64030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.64630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.65230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.65830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.66430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.67030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.67630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.68230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.68830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.69430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.70030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.70630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.71230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.71830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.72430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.73030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.73630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.74230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.74830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.75430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.76030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.76630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.77230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.77830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.78430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.79030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.79630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.80230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.80830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.81130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.81430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.81730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.82030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.82330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.82630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.82930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.83230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.83530_preprocessed.list',
	'/preprocessed_hlists/hlist_0.83830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.84130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.84430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.84730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.85030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.85330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.85630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.85930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.86230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.86530_preprocessed.list',
	'/preprocessed_hlists/hlist_0.86830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.87130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.87430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.87730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.88030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.88330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.88630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.88930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.89230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.89530_preprocessed.list',
	'/preprocessed_hlists/hlist_0.89830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.90130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.90430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.90730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.91030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.91330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.91630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.91930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.92230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.92530_preprocessed.list',
	'/preprocessed_hlists/hlist_0.92830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.93130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.93430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.93730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.94330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.94630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.94930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.95230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.95830_preprocessed.list',
	'/preprocessed_hlists/hlist_0.96130_preprocessed.list',
	'/preprocessed_hlists/hlist_0.96430_preprocessed.list',
	'/preprocessed_hlists/hlist_0.96730_preprocessed.list',
	'/preprocessed_hlists/hlist_0.97030_preprocessed.list',
	'/preprocessed_hlists/hlist_0.97330_preprocessed.list',
	'/preprocessed_hlists/hlist_0.97630_preprocessed.list',
	'/preprocessed_hlists/hlist_0.97930_preprocessed.list',
	'/preprocessed_hlists/hlist_0.98230_preprocessed.list',
	'/preprocessed_hlists/hlist_0.98530_preprocessed.list',
	'/preprocessed_hlists/hlist_0.99730_preprocessed.list',
]

times = []
failed = []
for f in file_names:
	# for each file in hadoop above, run the follwoing command
	started = time.time()
        try:
            subprocess.call('./../../bin/spark-submit --class "decision_tree" --master local[3] target/scala-2.10/simple-project_2.10-1.0.jar {}'.format(f), shell=True)
        except Exception, e:
        	# if anything fails, log it here
            print e
            failed.append(f)
	stopped = time.time()
	times.append(stopped - started)


# write the time in seconds it took to run each job to times.txt
with open('times.txt', 'w') as tf:
    tf.write('timings\n')
    tf.write(json.dumps(zip(file_names, times)))
    tf.write('\n')
    tf.write('failures\n')
    tf.write(json.dumps(failed))
    tf.write('\n')
