# SoftLayer API credentials
sl_username: "SL***"
sl_api_key: "***"
sl_ssh_keys: "***"
sl_private_key_path: "***"

# custom domain
sl_domain: "softlayer.com"

# datacenter where virtual servers should be provisioned
# datacenter = [ams01,dal01,dal05,dal06,hkg02,lon02,sea01,sjc01,sng01,wdc01]
sl_datacenter: "wdc01"

# virtual server parameters for BDAS cluster
# cpus = [1,2,4,8,12,16]
# memory = [1024,2048,4096,6144,8192,12288,16384,32768,49152,65536]
cpus: 2
memory: 4096
disk_capacity: 100
network_speed: 100

num_workers: 1
